//
//Copyright 2012 Google Inc.
//Copyright 2018-2025 Vimeo Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: galaxycachepb/galaxycache.proto

package galaxycachepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Galaxy string                 `protobuf:"bytes,1,opt,name=galaxy"`
	xxx_hidden_Key    []byte                 `protobuf:"bytes,2,opt,name=key"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_galaxycachepb_galaxycache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_galaxycachepb_galaxycache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRequest) GetGalaxy() string {
	if x != nil {
		return x.xxx_hidden_Galaxy
	}
	return ""
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *GetRequest) SetGalaxy(v string) {
	x.xxx_hidden_Galaxy = v
}

func (x *GetRequest) SetKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = v
}

type GetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Galaxy string
	Key    []byte
}

func (b0 GetRequest_builder) Build() *GetRequest {
	m0 := &GetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Galaxy = b.Galaxy
	x.xxx_hidden_Key = b.Key
	return m0
}

type GetResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value     []byte                 `protobuf:"bytes,1,opt,name=value"`
	xxx_hidden_MinuteQps float64                `protobuf:"fixed64,2,opt,name=minute_qps,json=minuteQps"`
	xxx_hidden_Expiry    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiry"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_galaxycachepb_galaxycache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_galaxycachepb_galaxycache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *GetResponse) GetMinuteQps() float64 {
	if x != nil {
		return x.xxx_hidden_MinuteQps
	}
	return 0
}

func (x *GetResponse) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Expiry
	}
	return nil
}

func (x *GetResponse) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
}

func (x *GetResponse) SetMinuteQps(v float64) {
	x.xxx_hidden_MinuteQps = v
}

func (x *GetResponse) SetExpiry(v *timestamppb.Timestamp) {
	x.xxx_hidden_Expiry = v
}

func (x *GetResponse) HasExpiry() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Expiry != nil
}

func (x *GetResponse) ClearExpiry() {
	x.xxx_hidden_Expiry = nil
}

type GetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value     []byte
	MinuteQps float64
	Expiry    *timestamppb.Timestamp
}

func (b0 GetResponse_builder) Build() *GetResponse {
	m0 := &GetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_MinuteQps = b.MinuteQps
	x.xxx_hidden_Expiry = b.Expiry
	return m0
}

type PeekRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Galaxy string                 `protobuf:"bytes,1,opt,name=galaxy"`
	xxx_hidden_Key    []byte                 `protobuf:"bytes,2,opt,name=key"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeekRequest) Reset() {
	*x = PeekRequest{}
	mi := &file_galaxycachepb_galaxycache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekRequest) ProtoMessage() {}

func (x *PeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_galaxycachepb_galaxycache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeekRequest) GetGalaxy() string {
	if x != nil {
		return x.xxx_hidden_Galaxy
	}
	return ""
}

func (x *PeekRequest) GetKey() []byte {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *PeekRequest) SetGalaxy(v string) {
	x.xxx_hidden_Galaxy = v
}

func (x *PeekRequest) SetKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = v
}

type PeekRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Galaxy string
	Key    []byte
}

func (b0 PeekRequest_builder) Build() *PeekRequest {
	m0 := &PeekRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Galaxy = b.Galaxy
	x.xxx_hidden_Key = b.Key
	return m0
}

type PeekResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value  []byte                 `protobuf:"bytes,1,opt,name=value"`
	xxx_hidden_Expiry *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiry"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeekResponse) Reset() {
	*x = PeekResponse{}
	mi := &file_galaxycachepb_galaxycache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekResponse) ProtoMessage() {}

func (x *PeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_galaxycachepb_galaxycache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeekResponse) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *PeekResponse) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Expiry
	}
	return nil
}

func (x *PeekResponse) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
}

func (x *PeekResponse) SetExpiry(v *timestamppb.Timestamp) {
	x.xxx_hidden_Expiry = v
}

func (x *PeekResponse) HasExpiry() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Expiry != nil
}

func (x *PeekResponse) ClearExpiry() {
	x.xxx_hidden_Expiry = nil
}

type PeekResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value  []byte
	Expiry *timestamppb.Timestamp
}

func (b0 PeekResponse_builder) Build() *PeekResponse {
	m0 := &PeekResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Expiry = b.Expiry
	return m0
}

var File_galaxycachepb_galaxycache_proto protoreflect.FileDescriptor

const file_galaxycachepb_galaxycache_proto_rawDesc = "" +
	"\n" +
	"\x1fgalaxycachepb/galaxycache.proto\x12\rgalaxycachepb\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\n" +
	"GetRequest\x12\x16\n" +
	"\x06galaxy\x18\x01 \x01(\tR\x06galaxy\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"v\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x1d\n" +
	"\n" +
	"minute_qps\x18\x02 \x01(\x01R\tminuteQps\x122\n" +
	"\x06expiry\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\"7\n" +
	"\vPeekRequest\x12\x16\n" +
	"\x06galaxy\x18\x01 \x01(\tR\x06galaxy\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"X\n" +
	"\fPeekResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x122\n" +
	"\x06expiry\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry2\x9c\x01\n" +
	"\vGalaxyCache\x12F\n" +
	"\vGetFromPeer\x12\x19.galaxycachepb.GetRequest\x1a\x1a.galaxycachepb.GetResponse\"\x00\x12E\n" +
	"\bPeekPeer\x12\x1a.galaxycachepb.PeekRequest\x1a\x1b.galaxycachepb.PeekResponse\"\x00B6Z*github.com/vimeo/galaxycache/galaxycachepb\x92\x03\a\xd2>\x02\x10\x03\b\x02b\beditionsp\xe8\a"

var file_galaxycachepb_galaxycache_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_galaxycachepb_galaxycache_proto_goTypes = []any{
	(*GetRequest)(nil),            // 0: galaxycachepb.GetRequest
	(*GetResponse)(nil),           // 1: galaxycachepb.GetResponse
	(*PeekRequest)(nil),           // 2: galaxycachepb.PeekRequest
	(*PeekResponse)(nil),          // 3: galaxycachepb.PeekResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_galaxycachepb_galaxycache_proto_depIdxs = []int32{
	4, // 0: galaxycachepb.GetResponse.expiry:type_name -> google.protobuf.Timestamp
	4, // 1: galaxycachepb.PeekResponse.expiry:type_name -> google.protobuf.Timestamp
	0, // 2: galaxycachepb.GalaxyCache.GetFromPeer:input_type -> galaxycachepb.GetRequest
	2, // 3: galaxycachepb.GalaxyCache.PeekPeer:input_type -> galaxycachepb.PeekRequest
	1, // 4: galaxycachepb.GalaxyCache.GetFromPeer:output_type -> galaxycachepb.GetResponse
	3, // 5: galaxycachepb.GalaxyCache.PeekPeer:output_type -> galaxycachepb.PeekResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_galaxycachepb_galaxycache_proto_init() }
func file_galaxycachepb_galaxycache_proto_init() {
	if File_galaxycachepb_galaxycache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_galaxycachepb_galaxycache_proto_rawDesc), len(file_galaxycachepb_galaxycache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_galaxycachepb_galaxycache_proto_goTypes,
		DependencyIndexes: file_galaxycachepb_galaxycache_proto_depIdxs,
		MessageInfos:      file_galaxycachepb_galaxycache_proto_msgTypes,
	}.Build()
	File_galaxycachepb_galaxycache_proto = out.File
	file_galaxycachepb_galaxycache_proto_goTypes = nil
	file_galaxycachepb_galaxycache_proto_depIdxs = nil
}
